version: "3.9"

services:
  # ─────────────────────────────────────────────
  # 1) Stable-Diffusion
  # ─────────────────────────────────────────────
  sd-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: sd-api:latest
    expose:
      - "8000"
    environment:
      - HF_TOKEN=${HF_TOKEN:-""}
    restart: unless-stopped
    # deploy:
    #   resources: { reservations: { devices: [ { capabilities: [ gpu ] } ] } }

  # ─────────────────────────────────────────────
  # 2) Nginx reverse proxy + load balancer
  # ─────────────────────────────────────────────
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - sd-api
    restart: unless-stopped
