FROM pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime

ENV HF_HUB_DISABLE_SYMLINKS_WARNING=1 \
    HF_TOKEN=${HF_TOKEN:-""}

COPY requirements.txt /tmp/
RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY app /app
WORKDIR /app

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
